
import './globals.css';
import { Inter, Inspiration } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Macareno NET',
  description: 'Generated by create next app',
}


export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={inter.style}>
        <h1>super titulo en el template</h1>
        {children}
      </body>
    </html>
  )
}
