
import './globals.css';
import { Inter, Inspiration } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const inspiration = Inspiration({ weight: '400', subsets: ['latin'] });
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">

      <body style={inter.style}>{children}</body>

    </html>
  )
}
